name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  test-no-lock:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Test
        run: npm test

  test-try:
    name: Additional Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}
    needs:
      - test
    strategy:
      matrix:
        scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-default-with-jquery
          - ember-classic
        include:
          - scenario:
              - ember-beta
              - ember-canary
            continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npx ember try:one ${{ matrix.scenario }} --- npm test
